---
- hosts: doma
  gather_facts: no
  become: yes
  roles:
    - base

- hosts: plankton.local
  gather_facts: no
  become: yes
  roles:
    - plex # set up user before storage
    - storage
    - dns_authority

  vars:
    storage_mount_point: /mnt/usbmedia
    storage_uuid: A6BCA8B3BCA88003
