---
- hosts: doma
  gather_facts: no
  become: yes
  roles:
    - base

  vars:
    static_ip_gateway: 192.168.1.1

    static_ip_by_host:
      patrick.local: 192.168.1.80
      squidward.local: 192.168.1.81

- hosts: squidward.local
  gather_facts: no
  become: yes
  roles:
    - storage

  vars:
    storage_mount_point: /mnt/usbmedia
    storage_uuid: A6BCA8B3BCA88003
