---
- hosts: doma
  gather_facts: no
  become: yes
  roles:
    - base

- hosts: patrick.local
  gather_facts: no
  become: yes
  roles:
    - storage

  vars:
    storage_mount_point: /mnt/usbmedia
    storage_uuid: A6BCA8B3BCA88003
