---
- hosts: doma
  gather_facts: no
  become: yes
  roles:
    - base

  vars:
    static_ip_gateway: 10.0.0.1

    static_ip_by_host:
      patrick.local: 10.0.0.20
      squidward.local: 10.0.0.21

- hosts: patrick.local
  gather_facts: no
  become: yes
  roles:
    - storage

  vars:
    storage_mount_point: /mnt/usbmedia
    storage_uuid: A6BCA8B3BCA88003
