- name: Set up authorized key from current user
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Update Raspberry Pi default user password
  when: replacement_pi_pass is defined
  become: true
  user:
    name: pi
    password: "{{ replacement_pi_pass | password_hash('sha512', 'ktotamstuchit') }}"
