- name: Install NTFS support
  apt:
    name: ntfs-3g
    state: present

- name: Mount point for USB-attached storage
  file:
    path: '{{ storage_mount_point }}'
    state: directory # permissions get reset on mount

# this relies on plex user having been created
- name: Set up USB-attached storage to auto-mount
  mount:
    path: '{{ storage_mount_point }}'
    src: UUID={{ storage_uuid }}
    fstype: ntfs
    opts: defaults,noatime,auto,nofail,noexec,nosuid,uid=plex,gid=plex,fmask=113,dmask=002
    state: present

- name: Get current mountpoints
  setup:
    gather_subset: [ hardware ]

- name: Mount the attached storage
  when: ansible_mounts | selectattr('mount', 'equalto', storage_mount_point) | list | length == 0
  command: mount -a
  args:
    warn: no # mount module does not perform refresh
