- name: Get current network information
  setup:
    gather_subset: [ network ]

- name: Static IP config for eth0
  become: yes
  copy:
    dest: /etc/network/interfaces.d/doma-static-ip-{{ ansible_host | replace('.', '-') }}
    content: |
      # static IP setup for doma-ansible network
      auto eth0
      iface eth0 inet static
          address {{ static_ip_by_host[ansible_host] }}/24
          gateway {{ static_ip_gateway }}

- name: Turn off DHCPCD management for eth0
  become: yes
  blockinfile:
    dest: /etc/dhcpcd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK: doma-ansible-base-static"
    block: |
      # avoid overriding static IP setup in /etc/network
      denyinterfaces eth0

# performing full reboot because could not reliably do network-only restart
- name: Restart box if intended IP is not currently active
  when: static_ip_by_host[ansible_host] not in ansible_all_ipv4_addresses
  become: yes
  reboot:
    msg: 'Rebooting to activate static IP {{ static_ip_by_host[ansible_host] }} (vs current IPs {{ ansible_all_ipv4_addresses }})'

# @todo put this in a separate role
- name: Mount point for USB-attached storage
  when: ansible_host == 'squidward.local'
  become: yes
  file:
    path: /mnt/usbwdelts
    state: directory # permissions get reset on mount

- name: Set up USB-attached storage to auto-mount
  when: ansible_host == 'squidward.local'
  become: yes
  mount:
    path: /mnt/usbwdelts
    src: UUID=A6BCA8B3BCA88003
    fstype: ntfs
    opts: defaults,noatime,auto,noexec,nosuid,uid=pi,gid=pi,fmask=133,dmask=022
    state: present

- name: Get current mountpoints
  setup:
    gather_subset: [ hardware ]

- name: Mount the attached storage
  when: (ansible_host == 'squidward.local') and (ansible_mounts | selectattr('mount', 'equalto', '/mnt/usbwdelts') | list | length == 0)
  become: yes
  command: mount -a
  args:
    warn: no # mount module does not perform refresh
