- name: Get current network information
  setup:
    gather_subset: [ network ]

- name: Static IP config for eth0
  copy:
    dest: /etc/network/interfaces.d/doma-static-ip-{{ ansible_host | replace('.', '-') }}
    content: |
      # static IP setup for doma-ansible network
      auto eth0
      iface eth0 inet static
          address {{ static_ip_by_host[ansible_host] }}/24
          gateway {{ static_ip_gateway }}

- name: Turn off DHCPCD management for eth0
  blockinfile:
    dest: /etc/dhcpcd.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK: doma-ansible-base-static"
    block: |
      # avoid overriding static IP setup in /etc/network
      denyinterfaces eth0

# performing full reboot because could not reliably do network-only restart
- name: Restart box if intended IP is not currently active
  when: static_ip_by_host[ansible_host] not in ansible_all_ipv4_addresses
  reboot:
    msg: 'Rebooting to activate static IP {{ static_ip_by_host[ansible_host] }} (vs current IPs {{ ansible_all_ipv4_addresses }})'
